serviceAccountName: argo
metadata:
  name: anomaly-detection
proxy: nil
image:
  base: intel/ai-workflows
  tlt: beta-tlt-anomaly-detection
  use_case: beta-anomaly-detection
workflow:
  config:
    training: finetuning
    inference: eval
dataset:
  type: <nfs/s3>
  nfs:
    server: nil
    path: nil
    subPath: nil
  s3:
    key: nil
